import { NextRequest } from "next/server";
import { createServerSupabaseClient } from "@/lib/supabase/server";
import {
  getRequestContext,
  getPaginationParams,
  unauthorized,
  serverError,
  success,
  created,
  badRequest,
  logAudit,
} from "@/lib/api/helpers";
import { invoiceSchema } from "@/lib/validations/invoice";

export async function GET(request: NextRequest) {
  try {
    const ctx = await getRequestContext();
    if (!ctx) return unauthorized();

    const url = new URL(request.url);
    const { page, limit, offset, sortBy, sortOrder } = getPaginationParams(url);

    const statusFilter = url.searchParams.get("status");
    const typeFilter = url.searchParams.get("type");
    const propertyId = url.searchParams.get("property_id");
    const overdueOnly = url.searchParams.get("overdue") === "true";

    const supabase = await createServerSupabaseClient();

    let query = (supabase
      .from("invoices") as any)
      .select(
        `*,
        property:properties(id, name, address_line1),
        work_order:work_orders(id, title, category),
        service_provider:service_providers(id, name)`,
        { count: "exact" }
      )
      .eq("organization_id", ctx.organizationId);

    if (statusFilter) query = query.eq("status", statusFilter);
    if (typeFilter) query = query.eq("type", typeFilter);
    if (propertyId) query = query.eq("property_id", propertyId);
    if (overdueOnly) {
      query = query
        .lt("due_date", new Date().toISOString().substring(0, 10))
        .not("status", "in", '("PAID","CANCELLED")');
    }

    query = query
      .order(sortBy, { ascending: sortOrder === "asc" })
      .range(offset, offset + limit - 1);

    const { data, count, error } = await query;
    if (error) return serverError(error);

    return success({
      data: data || [],
      total: count || 0,
      page,
      limit,
      totalPages: Math.ceil((count || 0) / limit),
    });
  } catch (err) {
    return serverError(err);
  }
}

export async function POST(request: NextRequest) {
  try {
    const ctx = await getRequestContext();
    if (!ctx) return unauthorized();

    const allowedRoles = ["SUPER_ADMIN", "ORG_ADMIN", "PROPERTY_MANAGER", "ACCOUNTANT"];
    if (!allowedRoles.includes(ctx.user.role)) {
      return badRequest("Insufficient permissions");
    }

    const body = await request.json();
    const parsed = invoiceSchema.safeParse(body);
    if (!parsed.success) return badRequest(parsed.error.issues[0].message);

    // Calculate amounts
    const subtotal = parsed.data.line_items.reduce(
      (sum, item) => sum + item.quantity * item.unit_price,
      0
    );
    const taxAmount = (subtotal * parsed.data.tax_rate) / 100;
    const totalAmount = subtotal + taxAmount - parsed.data.discount_amount;

    const supabase = await createServerSupabaseClient();

    const { data, error } = await (supabase
      .from("invoices") as any)
      .insert({
        ...parsed.data,
        organization_id: ctx.organizationId,
        created_by: ctx.user.id,
        invoice_number: "", // Auto-generated by trigger
        subtotal,
        tax_amount: taxAmount,
        total_amount: totalAmount,
        paid_amount: 0,
        status: "DRAFT",
      })
      .select(
        `*,
        property:properties(id, name),
        work_order:work_orders(id, title)`
      )
      .single();

    if (error) return serverError(error);

    await logAudit({
      organizationId: ctx.organizationId,
      userId: ctx.user.id,
      action: "CREATE",
      entityType: "invoice",
      entityId: data.id,
      changes: { total_amount: totalAmount },
    });

    return created(data);
  } catch (err) {
    return serverError(err);
  }
}
